#!/usr/bin/env bash

###############################################################################
# Frontend Snapshot Script
#
# Purpose: Capture complete frontend project state
# Usage: ./frontend-snapshot.sh [output_dir]
# Output: Creates timestamped snapshot in markdown and JSON formats
###############################################################################

set -euo pipefail

# Configuration
OUTPUT_DIR="${1:-.}"
TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
SNAPSHOT_FILE="${OUTPUT_DIR}/frontend_snapshot_${TIMESTAMP}.md"
JSON_FILE="${OUTPUT_DIR}/frontend_snapshot_${TIMESTAMP}.json"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Helper functions
log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

command_exists() {
    command -v "$1" >/dev/null 2>&1
}

###############################################################################
# Start Snapshot
###############################################################################

log_info "Starting frontend snapshot..."
log_info "Output file: ${SNAPSHOT_FILE}"

# Create output directory
mkdir -p "${OUTPUT_DIR}"

# Check if in Next.js project
if [[ ! -f "package.json" ]]; then
    log_error "Not in a Node.js project (no package.json found)"
    exit 1
fi

# Start markdown file
cat > "${SNAPSHOT_FILE}" <<EOF
# Frontend Project Snapshot

**Date:** $(date +"%Y-%m-%d %H:%M:%S %Z")
**Project:** $(pwd | xargs basename)
**Generated By:** frontend-snapshot.sh

---

## Project Information

EOF

# Start JSON file
cat > "${JSON_FILE}" <<EOF
{
  "snapshot_date": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")",
  "project_name": "$(pwd | xargs basename)",
EOF

###############################################################################
# Package.json Analysis
###############################################################################

log_info "Analyzing package.json..."

if [[ -f "package.json" ]]; then
    PROJECT_NAME=$(cat package.json | grep '"name"' | head -1 | sed 's/.*"name": "\(.*\)".*/\1/')
    PROJECT_VERSION=$(cat package.json | grep '"version"' | head -1 | sed 's/.*"version": "\(.*\)".*/\1/')

    cat >> "${SNAPSHOT_FILE}" <<EOF
### package.json

**Name:** ${PROJECT_NAME}
**Version:** ${PROJECT_VERSION}

EOF

    # Check for Next.js
    if grep -q "next" package.json; then
        NEXT_VERSION=$(cat package.json | grep '"next"' | sed 's/.*"next": "\(.*\)".*/\1/')
        cat >> "${SNAPSHOT_FILE}" <<EOF
**Framework:** Next.js ${NEXT_VERSION}

EOF
    fi

    # Check for React
    if grep -q "react" package.json; then
        REACT_VERSION=$(cat package.json | grep '"react"' | head -1 | sed 's/.*"react": "\(.*\)".*/\1/')
        cat >> "${SNAPSHOT_FILE}" <<EOF
**React Version:** ${REACT_VERSION}

EOF
    fi
fi

###############################################################################
# Dependencies
###############################################################################

log_info "Analyzing dependencies..."

cat >> "${SNAPSHOT_FILE}" <<EOF
### Dependencies

**Core Dependencies:**
\`\`\`json
$(cat package.json | jq '.dependencies' 2>/dev/null || echo "{}")
\`\`\`

**Dev Dependencies:**
\`\`\`json
$(cat package.json | jq '.devDependencies' 2>/dev/null || echo "{}")
\`\`\`

EOF

###############################################################################
# Scripts
###############################################################################

log_info "Analyzing npm scripts..."

cat >> "${SNAPSHOT_FILE}" <<EOF
### NPM Scripts

\`\`\`json
$(cat package.json | jq '.scripts' 2>/dev/null || echo "{}")
\`\`\`

EOF

###############################################################################
# Project Structure
###############################################################################

log_info "Analyzing project structure..."

cat >> "${SNAPSHOT_FILE}" <<EOF
### Project Structure

\`\`\`
EOF

if command_exists tree; then
    tree -L 3 -I 'node_modules|.next|out|dist|build|.git' >> "${SNAPSHOT_FILE}" 2>/dev/null || \
    find . -maxdepth 3 -not -path "*/node_modules/*" -not -path "*/.next/*" -not -path "*/out/*" -not -path "*/.git/*" 2>/dev/null | head -100 >> "${SNAPSHOT_FILE}"
else
    find . -maxdepth 3 -not -path "*/node_modules/*" -not -path "*/.next/*" -not -path "*/out/*" -not -path "*/.git/*" 2>/dev/null | head -100 >> "${SNAPSHOT_FILE}"
fi

cat >> "${SNAPSHOT_FILE}" <<EOF
\`\`\`

EOF

###############################################################################
# Configuration Files
###############################################################################

log_info "Checking configuration files..."

cat >> "${SNAPSHOT_FILE}" <<EOF
### Configuration Files

EOF

# Next.js config
if [[ -f "next.config.js" ]] || [[ -f "next.config.mjs" ]]; then
    cat >> "${SNAPSHOT_FILE}" <<EOF
**Next.js Config:** ✅ Present

EOF
fi

# TypeScript config
if [[ -f "tsconfig.json" ]]; then
    cat >> "${SNAPSHOT_FILE}" <<EOF
**TypeScript Config:** ✅ Present

\`\`\`json
$(cat tsconfig.json 2>/dev/null)
\`\`\`

EOF
fi

# Tailwind config
if [[ -f "tailwind.config.ts" ]] || [[ -f "tailwind.config.js" ]]; then
    cat >> "${SNAPSHOT_FILE}" <<EOF
**Tailwind Config:** ✅ Present

EOF
fi

# ESLint config
if [[ -f ".eslintrc.json" ]] || [[ -f ".eslintrc.js" ]]; then
    cat >> "${SNAPSHOT_FILE}" <<EOF
**ESLint Config:** ✅ Present

EOF
fi

# Prettier config
if [[ -f ".prettierrc" ]] || [[ -f ".prettierrc.json" ]]; then
    cat >> "${SNAPSHOT_FILE}" <<EOF
**Prettier Config:** ✅ Present

EOF
fi

###############################################################################
# Environment Variables
###############################################################################

log_info "Checking environment files..."

cat >> "${SNAPSHOT_FILE}" <<EOF
### Environment Files

EOF

if [[ -f ".env.local" ]]; then
    cat >> "${SNAPSHOT_FILE}" <<EOF
**.env.local:** ✅ Present
\`\`\`
$(cat .env.local 2>/dev/null | grep -v '=' | head -20)
# (values hidden for security)
\`\`\`

EOF
fi

if [[ -f ".env.example" ]]; then
    cat >> "${SNAPSHOT_FILE}" <<EOF
**.env.example:** ✅ Present
\`\`\`
$(cat .env.example 2>/dev/null | head -20)
\`\`\`

EOF
fi

###############################################################################
# Components Analysis
###############################################################################

log_info "Analyzing components..."

cat >> "${SNAPSHOT_FILE}" <<EOF
### Components Overview

EOF

# Count components
if [[ -d "src/components" ]]; then
    TOTAL_COMPONENTS=$(find src/components -name "*.tsx" -o -name "*.jsx" 2>/dev/null | wc -l | tr -d ' ')
    UI_COMPONENTS=$(find src/components/ui -name "*.tsx" -o -name "*.jsx" 2>/dev/null | wc -l | tr -d ' ')

    cat >> "${SNAPSHOT_FILE}" <<EOF
**Total Components:** ${TOTAL_COMPONENTS}
**UI Components:** ${UI_COMPONENTS}

**Component Structure:**
\`\`\`
$(find src/components -type f \( -name "*.tsx" -o -name "*.jsx" \) 2>/dev/null | head -30)
\`\`\`

EOF
elif [[ -d "components" ]]; then
    TOTAL_COMPONENTS=$(find components -name "*.tsx" -o -name "*.jsx" 2>/dev/null | wc -l | tr -d ' ')

    cat >> "${SNAPSHOT_FILE}" <<EOF
**Total Components:** ${TOTAL_COMPONENTS}

**Component Structure:**
\`\`\`
$(find components -type f \( -name "*.tsx" -o -name "*.jsx" \) 2>/dev/null | head -30)
\`\`\`

EOF
fi

###############################################################################
# Pages/Routes Analysis
###############################################################################

log_info "Analyzing routes..."

cat >> "${SNAPSHOT_FILE}" <<EOF
### Routes

EOF

if [[ -d "src/app" ]]; then
    cat >> "${SNAPSHOT_FILE}" <<EOF
**App Router (Next.js 13+):** ✅ Enabled

**Routes:**
\`\`\`
$(find src/app -name "page.tsx" -o -name "page.jsx" 2>/dev/null)
\`\`\`

**Layouts:**
\`\`\`
$(find src/app -name "layout.tsx" -o -name "layout.jsx" 2>/dev/null)
\`\`\`

EOF
elif [[ -d "app" ]]; then
    cat >> "${SNAPSHOT_FILE}" <<EOF
**App Router (Next.js 13+):** ✅ Enabled

**Routes:**
\`\`\`
$(find app -name "page.tsx" -o -name "page.jsx" 2>/dev/null)
\`\`\`

EOF
fi

if [[ -d "src/pages" ]] || [[ -d "pages" ]]; then
    cat >> "${SNAPSHOT_FILE}" <<EOF
**Pages Router:** ✅ Enabled

**Pages:**
\`\`\`
$(find src/pages pages -name "*.tsx" -o -name "*.jsx" 2>/dev/null | grep -v "_app\|_document")
\`\`\`

EOF
fi

###############################################################################
# API Routes
###############################################################################

log_info "Analyzing API routes..."

if [[ -d "src/app/api" ]] || [[ -d "app/api" ]] || [[ -d "src/pages/api" ]] || [[ -d "pages/api" ]]; then
    cat >> "${SNAPSHOT_FILE}" <<EOF
### API Routes

\`\`\`
$(find src/app/api app/api src/pages/api pages/api -name "*.ts" -o -name "*.js" 2>/dev/null)
\`\`\`

EOF
fi

###############################################################################
# Styles
###############################################################################

log_info "Analyzing styles..."

cat >> "${SNAPSHOT_FILE}" <<EOF
### Styling

EOF

# Tailwind
if [[ -f "tailwind.config.ts" ]] || [[ -f "tailwind.config.js" ]]; then
    cat >> "${SNAPSHOT_FILE}" <<EOF
**Tailwind CSS:** ✅ Configured

EOF
fi

# Global CSS
if [[ -f "src/app/globals.css" ]]; then
    GLOBAL_CSS_LINES=$(wc -l < "src/app/globals.css" | tr -d ' ')
    cat >> "${SNAPSHOT_FILE}" <<EOF
**Global CSS:** src/app/globals.css (${GLOBAL_CSS_LINES} lines)

EOF
fi

###############################################################################
# State Management
###############################################################################

log_info "Checking state management..."

cat >> "${SNAPSHOT_FILE}" <<EOF
### State Management

EOF

if grep -q "zustand" package.json 2>/dev/null; then
    cat >> "${SNAPSHOT_FILE}" <<EOF
**Zustand:** ✅ Installed

EOF
fi

if grep -q "jotai" package.json 2>/dev/null; then
    cat >> "${SNAPSHOT_FILE}" <<EOF
**Jotai:** ✅ Installed

EOF
fi

if grep -q "@tanstack/react-query" package.json 2>/dev/null; then
    cat >> "${SNAPSHOT_FILE}" <<EOF
**TanStack Query:** ✅ Installed

EOF
fi

###############################################################################
# UI Libraries
###############################################################################

log_info "Checking UI libraries..."

cat >> "${SNAPSHOT_FILE}" <<EOF
### UI Libraries

EOF

if grep -q "shadcn" package.json 2>/dev/null || [[ -f "components.json" ]]; then
    cat >> "${SNAPSHOT_FILE}" <<EOF
**shadcn/ui:** ✅ Configured

EOF
fi

if grep -q "lucide-react" package.json 2>/dev/null; then
    cat >> "${SNAPSHOT_FILE}" <<EOF
**Lucide Icons:** ✅ Installed

EOF
fi

###############################################################################
# Build Info
###############################################################################

log_info "Checking build configuration..."

cat >> "${SNAPSHOT_FILE}" <<EOF
### Build Configuration

EOF

# Node version
if command_exists node; then
    NODE_VERSION=$(node --version 2>/dev/null || echo "Not available")
    cat >> "${SNAPSHOT_FILE}" <<EOF
**Node.js:** ${NODE_VERSION}

EOF
fi

# pnpm version
if command_exists pnpm; then
    PNPM_VERSION=$(pnpm --version 2>/dev/null || echo "Not available")
    cat >> "${SNAPSHOT_FILE}" <<EOF
**pnpm:** ${PNPM_VERSION}

EOF
fi

# npm version
if command_exists npm; then
    NPM_VERSION=$(npm --version 2>/dev/null || echo "Not available")
    cat >> "${SNAPSHOT_FILE}" <<EOF
**npm:** ${NPM_VERSION}

EOF
fi

# Yarn version
if command_exists yarn; then
    YARN_VERSION=$(yarn --version 2>/dev/null || echo "Not available")
    cat >> "${SNAPSHOT_FILE}" <<EOF
**yarn:** ${YARN_VERSION}

EOF
fi

###############################################################################
# Git Info
###############################################################################

if command_exists git && [[ -d ".git" ]]; then
    log_info "Capturing Git information..."

    cat >> "${SNAPSHOT_FILE}" <<EOF
### Git Information

**Current Branch:** $(git branch --show-current 2>/dev/null || echo "Unknown")
**Latest Commit:** $(git log -1 --pretty=format:"%h - %s" 2>/dev/null || echo "Unknown")

**Status:**
\`\`\`
$(git status --short 2>/dev/null | head -20)
\`\`\`

EOF
fi

###############################################################################
# Bundle Analysis (if .next exists)
###############################################################################

if [[ -d ".next" ]]; then
    log_info "Checking build artifacts..."

    cat >> "${SNAPSHOT_FILE}" <<EOF
### Build Artifacts

**.next folder:** ✅ Present (built)

EOF

    if [[ -d ".next/static" ]]; then
        STATIC_SIZE=$(du -sh .next/static 2>/dev/null | cut -f1 || echo "Unknown")
        cat >> "${SNAPSHOT_FILE}" <<EOF
**Static Assets Size:** ${STATIC_SIZE}

EOF
    fi
fi

###############################################################################
# Deployment Info
###############################################################################

log_info "Checking deployment configuration..."

cat >> "${SNAPSHOT_FILE}" <<EOF
### Deployment

EOF

if [[ -f "vercel.json" ]]; then
    cat >> "${SNAPSHOT_FILE}" <<EOF
**Vercel:** ✅ Configured (vercel.json present)

EOF
fi

if [[ -f ".github/workflows/deploy.yml" ]] || [[ -f ".github/workflows/deploy.yaml" ]]; then
    cat >> "${SNAPSHOT_FILE}" <<EOF
**GitHub Actions:** ✅ Configured

EOF
fi

if [[ -f "Dockerfile" ]]; then
    cat >> "${SNAPSHOT_FILE}" <<EOF
**Docker:** ✅ Configured (Dockerfile present)

EOF
fi

###############################################################################
# Testing
###############################################################################

log_info "Checking testing setup..."

cat >> "${SNAPSHOT_FILE}" <<EOF
### Testing

EOF

if grep -q "vitest" package.json 2>/dev/null; then
    TEST_FILES=$(find . -name "*.test.tsx" -o -name "*.test.ts" -o -name "*.spec.tsx" -o -name "*.spec.ts" 2>/dev/null | wc -l | tr -d ' ')
    cat >> "${SNAPSHOT_FILE}" <<EOF
**Vitest:** ✅ Installed
**Test Files:** ${TEST_FILES}

EOF
fi

if grep -q "playwright" package.json 2>/dev/null; then
    cat >> "${SNAPSHOT_FILE}" <<EOF
**Playwright:** ✅ Installed (E2E testing)

EOF
fi

###############################################################################
# Finalize
###############################################################################

cat >> "${SNAPSHOT_FILE}" <<EOF
---

**Snapshot completed:** $(date +"%Y-%m-%d %H:%M:%S %Z")

---

## Usage Notes

This snapshot captures the frontend project state at a point in time. Use it to:
- Document project setup
- Compare configurations across projects
- Track changes over time
- Onboard new developers
- Debug environment issues

Compare future snapshots to this baseline to track project evolution.
EOF

# Close JSON
cat >> "${JSON_FILE}" <<EOF
  "completed": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
}
EOF

###############################################################################
# Summary
###############################################################################

log_info "Snapshot complete!"
echo ""
log_info "Files created:"
echo "  - Markdown: ${SNAPSHOT_FILE}"
echo "  - JSON:     ${JSON_FILE}"
echo ""

# Display quick summary
if [[ -f "package.json" ]]; then
    echo "Quick Summary:"
    echo "=============="
    echo "Project: $(cat package.json | jq -r '.name' 2>/dev/null || echo 'Unknown')"
    echo "Version: $(cat package.json | jq -r '.version' 2>/dev/null || echo 'Unknown')"

    if grep -q "next" package.json; then
        echo "Framework: Next.js"
    fi

    if [[ -d "src/components" ]]; then
        COMPONENT_COUNT=$(find src/components -name "*.tsx" -o -name "*.jsx" 2>/dev/null | wc -l | tr -d ' ')
        echo "Components: ${COMPONENT_COUNT}"
    fi

    if [[ -d ".next" ]]; then
        echo "Build: ✅ Compiled"
    else
        echo "Build: ❌ Not built"
    fi
fi

log_info "Review the snapshot before proceeding with changes."
