#!/usr/bin/env bash

###############################################################################
# Infrastructure Snapshot Script
#
# Purpose: Capture complete system state before starting a new project
# Usage: ./infrastructure-snapshot.sh [output_dir]
# Output: Creates timestamped snapshot in markdown and JSON formats
###############################################################################

set -euo pipefail

# Configuration
OUTPUT_DIR="${1:-.}"
TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
SNAPSHOT_FILE="${OUTPUT_DIR}/infrastructure_snapshot_${TIMESTAMP}.md"
JSON_FILE="${OUTPUT_DIR}/infrastructure_snapshot_${TIMESTAMP}.json"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Helper functions
log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

command_exists() {
    command -v "$1" >/dev/null 2>&1
}

###############################################################################
# Start Snapshot
###############################################################################

log_info "Starting infrastructure snapshot..."
log_info "Output file: ${SNAPSHOT_FILE}"

# Create output directory if needed
mkdir -p "${OUTPUT_DIR}"

# Start markdown file
cat > "${SNAPSHOT_FILE}" <<EOF
# Infrastructure Snapshot

**Date:** $(date +"%Y-%m-%d %H:%M:%S %Z")
**Hostname:** $(hostname)
**Generated By:** infrastructure-snapshot.sh

---

## System Information

EOF

# Start JSON file
cat > "${JSON_FILE}" <<EOF
{
  "snapshot_date": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")",
  "hostname": "$(hostname)",
EOF

###############################################################################
# OS Information
###############################################################################

log_info "Capturing OS information..."

cat >> "${SNAPSHOT_FILE}" <<EOF
### Operating System

EOF

if [[ -f /etc/os-release ]]; then
    cat >> "${SNAPSHOT_FILE}" <<EOF
\`\`\`
$(cat /etc/os-release)
\`\`\`

EOF
fi

cat >> "${SNAPSHOT_FILE}" <<EOF
**Kernel:** $(uname -r)
**Architecture:** $(uname -m)
**Uptime:** $(uptime)

EOF

###############################################################################
# CPU Information
###############################################################################

log_info "Capturing CPU information..."

cat >> "${SNAPSHOT_FILE}" <<EOF
### CPU

EOF

if command_exists lscpu; then
    CPU_MODEL=$(lscpu | grep "Model name" | cut -d: -f2 | xargs)
    CPU_CORES=$(lscpu | grep "^CPU(s):" | cut -d: -f2 | xargs)
    CPU_THREADS=$(lscpu | grep "Thread(s) per core" | cut -d: -f2 | xargs)

    cat >> "${SNAPSHOT_FILE}" <<EOF
- **Model:** ${CPU_MODEL}
- **Cores:** ${CPU_CORES}
- **Threads per core:** ${CPU_THREADS}

**Full CPU Info:**
\`\`\`
$(lscpu)
\`\`\`

EOF
elif [[ -f /proc/cpuinfo ]]; then
    cat >> "${SNAPSHOT_FILE}" <<EOF
\`\`\`
$(cat /proc/cpuinfo | head -20)
\`\`\`

EOF
fi

###############################################################################
# Memory Information
###############################################################################

log_info "Capturing memory information..."

cat >> "${SNAPSHOT_FILE}" <<EOF
### Memory

EOF

if command_exists free; then
    cat >> "${SNAPSHOT_FILE}" <<EOF
\`\`\`
$(free -h)
\`\`\`

EOF

    TOTAL_RAM=$(free -h | awk '/^Mem:/ {print $2}')
    USED_RAM=$(free -h | awk '/^Mem:/ {print $3}')
    FREE_RAM=$(free -h | awk '/^Mem:/ {print $4}')

    cat >> "${SNAPSHOT_FILE}" <<EOF
**Summary:**
- Total: ${TOTAL_RAM}
- Used: ${USED_RAM}
- Free: ${FREE_RAM}

EOF
fi

###############################################################################
# Disk Information
###############################################################################

log_info "Capturing disk information..."

cat >> "${SNAPSHOT_FILE}" <<EOF
### Disk

\`\`\`
$(df -h | grep -v "tmpfs\|devtmpfs" || true)
\`\`\`

EOF

if command_exists lsblk; then
    cat >> "${SNAPSHOT_FILE}" <<EOF
**Block Devices:**
\`\`\`
$(lsblk)
\`\`\`

EOF
fi

###############################################################################
# Network Information
###############################################################################

log_info "Capturing network information..."

cat >> "${SNAPSHOT_FILE}" <<EOF
### Network

EOF

if command_exists ip; then
    cat >> "${SNAPSHOT_FILE}" <<EOF
**IP Addresses:**
\`\`\`
$(ip addr show)
\`\`\`

EOF
fi

if command_exists ss; then
    cat >> "${SNAPSHOT_FILE}" <<EOF
**Listening Ports:**
\`\`\`
$(sudo ss -tulpn 2>/dev/null || ss -tuln)
\`\`\`

EOF
elif command_exists netstat; then
    cat >> "${SNAPSHOT_FILE}" <<EOF
**Listening Ports:**
\`\`\`
$(sudo netstat -tulpn 2>/dev/null || netstat -tuln)
\`\`\`

EOF
fi

###############################################################################
# Software Versions
###############################################################################

log_info "Capturing installed software versions..."

cat >> "${SNAPSHOT_FILE}" <<EOF
### Installed Software

EOF

# Docker
if command_exists docker; then
    DOCKER_VERSION=$(docker --version 2>/dev/null || echo "Not available")
    cat >> "${SNAPSHOT_FILE}" <<EOF
**Docker:** ${DOCKER_VERSION}

EOF
fi

# Docker Compose
if command_exists docker-compose || command_exists docker compose; then
    if command_exists docker-compose; then
        COMPOSE_VERSION=$(docker-compose --version 2>/dev/null || echo "Not available")
    else
        COMPOSE_VERSION=$(docker compose version 2>/dev/null || echo "Not available")
    fi
    cat >> "${SNAPSHOT_FILE}" <<EOF
**Docker Compose:** ${COMPOSE_VERSION}

EOF
fi

# Nginx
if command_exists nginx; then
    NGINX_VERSION=$(nginx -v 2>&1 || echo "Not available")
    cat >> "${SNAPSHOT_FILE}" <<EOF
**Nginx:** ${NGINX_VERSION}

EOF
fi

# Node.js
if command_exists node; then
    NODE_VERSION=$(node --version 2>/dev/null || echo "Not available")
    cat >> "${SNAPSHOT_FILE}" <<EOF
**Node.js:** ${NODE_VERSION}

EOF
fi

# npm
if command_exists npm; then
    NPM_VERSION=$(npm --version 2>/dev/null || echo "Not available")
    cat >> "${SNAPSHOT_FILE}" <<EOF
**npm:** ${NPM_VERSION}

EOF
fi

# Python
if command_exists python3; then
    PYTHON_VERSION=$(python3 --version 2>/dev/null || echo "Not available")
    cat >> "${SNAPSHOT_FILE}" <<EOF
**Python:** ${PYTHON_VERSION}

EOF
fi

# Git
if command_exists git; then
    GIT_VERSION=$(git --version 2>/dev/null || echo "Not available")
    cat >> "${SNAPSHOT_FILE}" <<EOF
**Git:** ${GIT_VERSION}

EOF
fi

###############################################################################
# Docker Containers (if Docker is installed)
###############################################################################

if command_exists docker; then
    log_info "Capturing Docker containers..."

    cat >> "${SNAPSHOT_FILE}" <<EOF
### Docker Containers

\`\`\`
$(docker ps -a 2>/dev/null || echo "Unable to query Docker")
\`\`\`

**Images:**
\`\`\`
$(docker images 2>/dev/null || echo "Unable to query Docker")
\`\`\`

**Networks:**
\`\`\`
$(docker network ls 2>/dev/null || echo "Unable to query Docker")
\`\`\`

**Volumes:**
\`\`\`
$(docker volume ls 2>/dev/null || echo "Unable to query Docker")
\`\`\`

EOF
fi

###############################################################################
# System Services
###############################################################################

log_info "Capturing system services..."

cat >> "${SNAPSHOT_FILE}" <<EOF
### System Services

EOF

if command_exists systemctl; then
    cat >> "${SNAPSHOT_FILE}" <<EOF
**Active Services:**
\`\`\`
$(systemctl list-units --type=service --state=running --no-pager 2>/dev/null || echo "Unable to query systemctl")
\`\`\`

EOF
fi

###############################################################################
# Resource Usage
###############################################################################

log_info "Capturing current resource usage..."

cat >> "${SNAPSHOT_FILE}" <<EOF
### Current Resource Usage

EOF

if command_exists top; then
    cat >> "${SNAPSHOT_FILE}" <<EOF
**Top Processes:**
\`\`\`
$(top -bn1 | head -20)
\`\`\`

EOF
fi

if command_exists docker && docker ps -q &>/dev/null; then
    cat >> "${SNAPSHOT_FILE}" <<EOF
**Docker Stats:**
\`\`\`
$(docker stats --no-stream --no-trunc 2>/dev/null || echo "Unable to query Docker stats")
\`\`\`

EOF
fi

###############################################################################
# Environment
###############################################################################

log_info "Capturing environment information..."

cat >> "${SNAPSHOT_FILE}" <<EOF
### Environment

**User:** $(whoami)
**Home:** ${HOME}
**Shell:** ${SHELL}
**PATH:** ${PATH}

EOF

###############################################################################
# Finalize
###############################################################################

cat >> "${SNAPSHOT_FILE}" <<EOF
---

**Snapshot completed:** $(date +"%Y-%m-%d %H:%M:%S %Z")

---

## Usage Notes

This snapshot was taken before starting a new project. Use it to:
- Assess available resources
- Identify potential port conflicts
- Document baseline system state
- Plan resource allocation

Compare future snapshots to this baseline to track infrastructure changes over time.
EOF

# Close JSON
cat >> "${JSON_FILE}" <<EOF
  "completed": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
}
EOF

###############################################################################
# Summary
###############################################################################

log_info "Snapshot complete!"
echo ""
log_info "Files created:"
echo "  - Markdown: ${SNAPSHOT_FILE}"
echo "  - JSON:     ${JSON_FILE}"
echo ""

# Display summary
if command_exists free && command_exists df; then
    echo "Quick Summary:"
    echo "=============="
    echo "Memory: $(free -h | awk '/^Mem:/ {print $3 "/" $2 " used (" $3/$2*100 "%)"}')"
    echo "Disk:   $(df -h / | awk 'NR==2 {print $3 "/" $2 " used (" $5 ")"}')"
    if command_exists docker; then
        CONTAINER_COUNT=$(docker ps -q 2>/dev/null | wc -l | tr -d ' ')
        echo "Docker: ${CONTAINER_COUNT} containers running"
    fi
fi

log_info "Review the snapshot before proceeding with your project."
